---
title: "Taper Functions for poplar plantations"
output:
  pdf_document:
    toc: true
---
  
# General scope
Assessment of poplar profiles sensitivity against plantation density and competition anisotropy

# Setup and fetch the data

```{r read-data}
library(tidyverse)
library(magrittr)
library(ggplot2)
source("ReadData.R", echo = T)

```


# Compute diameters
(directly, not through Radius)

```{r diameters}

cooX <- dsin %>% select(-Y, -Z) %>% spread(id_lato, X) %>%
  rename(
    xe1 = interfila_piena,
    xe2 = interfila_vuota,
    xa1 = intrafila_alto,
    xa2 = intrafila_basso
  )

cooY <-
  dsin %>% select(-X, -Z) %>% spread(id_lato, Y) %>%
  rename(
    ye1 = interfila_piena,
    ye2 = interfila_vuota,
    ya1 = intrafila_alto,
    ya2 = intrafila_basso
  )

Diameters <- cooX %>%
  full_join(cooY) %>%
  mutate(btw_rows = sqrt((xe1 - xe2) ^ 2 + (ye1 - ye2) ^ 2),
         wti_rows = sqrt((xa1 - xa2) ^ 2 + (ya1 - ya2) ^ 2)) %>%
  select(-xe1,-xe2,-xa1,-xa2,-ye1,-ye2,-ya1,-ya2) %>%
  gather(direction, diam,-tesi,-length_toppo,-treid,-slice)

```

# Plot all profiles

```{r plot, fig.height=9, fig.width=7}
gl <- Diameters %$%
  levels(tesi) %>%
  map(
    ~ Diameters %>%
      filter(tesi == .x) %>%
      ggplot(aes(slice, diam)) +
      geom_line(aes(color = direction)) +
      facet_grid(treid ~ length_toppo, scales = "free") +
      ggtitle(paste0("Tesis: '", .x, "'")) +
      theme(plot.title = element_text(hjust = 0.5))
  )
print(gl)

```
