---
title: "Taper Functions for poplar plantations"
output:
  pdf_document:
    toc: true
---
  
# General scope
Assessment of poplar profiles sensitivity against plantation density and competition anisotropy  
[MEMO: credo sia opportuno ricordarsi di citare
 Rubio-Cuadrado Á, Bravo-Oviedo A, Mutke S, Del Río M (2018). Climate effects on growth differ according to height and diameter
along the stem in Pinus pinaster Ait. iForest 11: 237-242. – doi: 10.3832/ifor2318-011 [online 2018-03-12]

# Setup and fetch the data

```{r read-data}
library(tidyverse)
library(magrittr)
library(ggplot2)
source('ReadData.R')
tff <- TLSderivedDiam %>%
  inner_join(stems_basic_measurements, 
             by = c("tesi" = "Tesi", "treid" = "TreeId")) %>%
  mutate(deltad = diam_btw_rows - diam_wti_rows)

```


```{r}
oll <- 0.5 # Optimal Log Length
# length_toppo ottimale: compromesso tra min lag correlation e conservazione del dettaglio della forma
tff  %>%
  filter(length_toppo == oll) %$%
  anova(lm(deltad ~ tesi + (slice * treid) + DBH + Htot))

```


# Plot all profiles

```{r plot, fig.height=9, fig.width=7}
Diameters <- TLSderivedDiam %>% 
  select( -ends_with("centro")) %>% 
  gather(direction, diam, starts_with("diam"))

gl <- Diameters %$%
  levels(tesi) %>%
  map(
    ~ Diameters %>%
      filter(tesi == .x) %>%
      ggplot(aes(slice, diam)) +
      geom_line(aes(color = direction)) +
      facet_grid(treid ~ length_toppo, scales = "free") +
      ggtitle(paste0("Tesis: '", .x, "'")) +
      theme(plot.title = element_text(hjust = 0.5))
  )
print(gl)

```


```{r}

```



```{r}
library(TapeR)
oll <- 0.5 # Optimal Log Length
# length_toppo ottimale: compromesso tra min lag correlation e conservazione del dettaglio della forma

#define the relative knot positions and order of splines
knt_x = c(0.0, 0.1, 0.5, 1.0); ord_x = 2 # B-Spline knots: fix effects; order (cubic = 4)
knt_z = c(0.0, 0.1     , 1.0); ord_z = 2 # B-Spline knots: rnd effects

max_hsez <- max(Diameters$slice)
tff <- TLSderivedDiam %>%
  filter(length_toppo == oll, tesi == 'V400') %>%
  inner_join(stems_basic_measurements, 
             by = c("tesi" = "Tesi", "treid" = "TreeId")) %>%
  transmute(Id = paste0(tesi ,treid), 
         d_sez = diam_wti_rows *100, 
         rel_h = slice / max_hsez) %$%
  TapeR_FIT_LME.f(Id, d_sez, rel_h, knt_x, ord_x, knt_z, ord_z, IdKOVb = "pdSymm")
#fit the model

```

